package notify

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"

	"github.com/darpanzope/compliancekit/pkg/compliancekit"
)

// GitHubConfig configures the GitHub PR comment sink. Posts one
// summary comment per dispatch (NOT per finding) to avoid PR-comment
// spam — the comment lists every notification as a markdown bullet.
//
// The token needs `pull_requests:write` (fine-grained) or `repo`
// (classic). For the GitHub Action use case, GITHUB_TOKEN already
// has it; for ad-hoc runs the operator generates a PAT.
//
// Env: GITHUB_TOKEN, GITHUB_REPO ("owner/name"), GITHUB_PR_NUMBER,
// GITHUB_API_URL (override for GHES), GITHUB_THRESHOLD.
type GitHubConfig struct {
	Token         string
	Repo          string // owner/name
	PRNumber      int
	APIURL        string // defaults to https://api.github.com
	SeverityFloor compliancekit.Severity
	HTTPClient    *http.Client
}

// GitHub implements Notifier for GitHub PR comments.
type GitHub struct{ cfg GitHubConfig }

// NewGitHub constructs a GitHub sink.
func NewGitHub(cfg GitHubConfig) *GitHub {
	if cfg.APIURL == "" {
		cfg.APIURL = "https://api.github.com"
	}
	return &GitHub{cfg: cfg}
}

// Name implements Notifier.
func (g *GitHub) Name() string { return "github-pr" }

// Configured returns true when token + repo + PR number are set.
func (g *GitHub) Configured() bool {
	return g.cfg.Token != "" && g.cfg.Repo != "" && g.cfg.PRNumber > 0
}

// Threshold returns the per-sink severity floor.
func (g *GitHub) Threshold() compliancekit.Severity { return g.cfg.SeverityFloor }

// Send posts a single summary comment to the PR. Each notification
// becomes a markdown bullet listing severity + title + link. The
// "one comment per dispatch" choice avoids the PR-comment spam that
// "one comment per finding" would produce on noisy scans.
func (g *GitHub) Send(ctx context.Context, notifications []Notification) (Result, error) {
	if len(notifications) == 0 {
		return Result{}, nil
	}
	body := g.buildCommentBody(notifications)
	if err := g.postComment(ctx, body); err != nil {
		return Result{
			Errors:   1,
			Messages: []string{fmt.Sprintf("github-pr: %v", err)},
		}, fmt.Errorf("github-pr: %w", err)
	}
	return Result{
		Sent:     len(notifications),
		Messages: []string{fmt.Sprintf("github-pr: posted single comment with %d findings", len(notifications))},
	}, nil
}

// buildCommentBody renders the summary comment. Format:
//
//	## compliancekit — N actionable findings
//
//	| Severity | Check | Resource | Detail |
//	| ... | ... | ... | ... |
//
//	_Generated by [compliancekit](https://github.com/darpanzope/compliancekit)._
func (g *GitHub) buildCommentBody(notifications []Notification) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "## compliancekit — %d actionable finding(s)\n\n", len(notifications))
	sb.WriteString("| Severity | Check | Resource | Detail |\n")
	sb.WriteString("|---|---|---|---|\n")
	for _, n := range notifications {
		resName := n.Finding.Resource.Name
		if resName == "" {
			resName = n.Finding.Resource.ID
		}
		detail := strings.ReplaceAll(n.Finding.Message, "|", "\\|")
		if n.URL != "" {
			detail = fmt.Sprintf("[%s](%s)", detail, n.URL)
		}
		fmt.Fprintf(&sb, "| %s | `%s` | `%s` | %s |\n",
			strings.ToUpper(n.Finding.Severity.String()),
			n.Finding.CheckID,
			resName,
			detail,
		)
	}
	sb.WriteString("\n_Generated by [compliancekit](https://github.com/darpanzope/compliancekit)._\n")
	return sb.String()
}

func (g *GitHub) postComment(ctx context.Context, body string) error {
	url := fmt.Sprintf("%s/repos/%s/issues/%d/comments",
		strings.TrimRight(g.cfg.APIURL, "/"),
		g.cfg.Repo,
		g.cfg.PRNumber,
	)
	payload := map[string]string{"body": body}
	raw, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	client := g.cfg.HTTPClient
	if client == nil {
		client = HTTPClient
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(raw))
	if err != nil {
		return fmt.Errorf("new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+g.cfg.Token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")
	req.Header.Set("User-Agent", "compliancekit/1.0")

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("transport: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	respBody, _ := io.ReadAll(resp.Body)
	switch {
	case resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusForbidden:
		return fmt.Errorf("%w: %s", ErrAuth, string(respBody))
	case resp.StatusCode >= 200 && resp.StatusCode < 300:
		return nil
	}
	return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))
}

func init() {
	cfg := GitHubConfig{
		Token:  os.Getenv("GITHUB_TOKEN"),
		Repo:   os.Getenv("GITHUB_REPO"),
		APIURL: os.Getenv("GITHUB_API_URL"),
	}
	if p := os.Getenv("GITHUB_PR_NUMBER"); p != "" {
		if n, err := strconv.Atoi(p); err == nil {
			cfg.PRNumber = n
		}
	}
	if t := os.Getenv("GITHUB_THRESHOLD"); t != "" {
		if sev, err := compliancekit.ParseSeverity(t); err == nil {
			cfg.SeverityFloor = sev
		}
	}
	Register(NewGitHub(cfg))
}
