{{- range $tag, $cfg := .Values.auth.saml.providers -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-saml-%s" (include "compliancekit.fullname" $) $tag }}
  labels:
    {{- include "compliancekit.labels" $ | nindent 4 }}
type: Opaque
stringData:
  spCertPem: {{ $cfg.spCertPem | quote }}
  spKeyPem: {{ $cfg.spKeyPem | quote }}
  {{- with $cfg.idpMetadataXml }}
  idpMetadataXml: {{ . | quote }}
  {{- end }}
---
{{ end -}}
