{{- range $tag, $cfg := .Values.auth.oidc.providers -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-oidc-%s" (include "compliancekit.fullname" $) $tag }}
  labels:
    {{- include "compliancekit.labels" $ | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ $cfg.clientSecret | quote }}
---
{{ end -}}
