{{- if and .Values.auth.scim.enabled (not .Values.auth.scim.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compliancekit.fullname" . }}-scim
  labels:
    {{- include "compliancekit.labels" . | nindent 4 }}
type: Opaque
stringData:
  bearer: {{ .Values.auth.scim.bearerToken | quote }}
{{- end -}}
