// v1.12 phase 3 — SAML 2.0 SSO via crewjam/saml.
//
// The daemon acts as a Service Provider (SP); the operator brings an
// Identity Provider (IdP) — Okta, Azure AD, Google Workspace, OneLogin,
// Auth0, etc. — and pastes its metadata into compliancekit.yaml. We
// expose two routes per configured SAML connection:
//
//	GET  /saml/{id}/login     SP-initiated AuthnRequest
//	POST /saml/{id}/acs       Assertion Consumer Service
//	GET  /saml/{id}/metadata  SP metadata XML (operator copies this
//	                          into their IdP)
//
// IdP-initiated SSO works too: the IdP posts an unsolicited assertion
// to /saml/{id}/acs, the SP verifies signature + audience + replay
// window, and the user lands on /.
//
// Mapping rule: the assertion's NameID is treated as the canonical
// email. If a local user with that email exists, the SAML login binds
// to it; otherwise a new user is provisioned (display name from the
// `displayName` attribute when present, else the email). Role
// assignments are NOT auto-granted — operators wire that via the
// phase 1 matrix UI or the phase 4 SCIM /Groups endpoint.

package auth

import (
	"context"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/crewjam/saml"
	"github.com/crewjam/saml/samlsp"
	"github.com/go-chi/chi/v5"

	"github.com/darpanzope/compliancekit/internal/server/store"
)

// SAMLConfig is one configured SAML SSO connection. Operators register
// one per IdP they accept logins from; the daemon supports many.
type SAMLConfig struct {
	// ID is the URL-safe identifier ("okta-corp", "azure-prod") that
	// namespaces every route + the SP metadata's EntityID.
	ID string

	// Label is the human display label, e.g. "Sign in with Okta".
	Label string

	// EntryPoint is the IdP's SingleSignOnService URL — the SP redirects
	// the browser here on /saml/{id}/login. Operators copy it from the
	// IdP metadata.
	EntryPoint string

	// IDPMetadataXML is the entire IdP metadata document. Used to
	// recover the IdP's signing certificate so the SP can verify
	// assertions. Mutually exclusive with IDPCertPEM.
	IDPMetadataXML string

	// IDPCertPEM is the IdP's signing cert in PEM. When the operator
	// can't / won't paste the whole metadata blob, this is the smallest
	// thing the SP needs.
	IDPCertPEM string

	// EntityID is the SP's own EntityID. Defaults to
	// {RootURL}/saml/{id}/metadata when empty.
	EntityID string

	// RootURL is the daemon's externally-visible URL ("https://compliancekit.example.com").
	// Used to build the ACS and metadata URLs.
	RootURL string

	// SPCertPEM + SPKeyPEM are the SP's signing keypair. Generated by
	// the operator (a short-lived self-signed cert works; the IdP only
	// uses it to verify SP-side message signatures).
	SPCertPEM string
	SPKeyPEM  string

	// AllowIDPInitiated permits unsolicited assertions. Defaults true
	// because every major IdP exposes "launch app" tiles that produce
	// IdP-initiated flows; disable when defense-in-depth matters more
	// than the convenience.
	AllowIDPInitiated bool

	// SignRequests asks the SP to sign outbound AuthnRequests. Defaults
	// off because not every IdP enforces signature verification on the
	// SP side; turn on when the IdP requires it.
	SignRequests bool
}

// SAMLProviderButton is the display-side projection of a SAMLConfig
// for rendering on the /login page alongside OIDCProviderButton.
type SAMLProviderButton struct {
	ID    string // url-safe id; matches the /saml/{id}/login path
	Label string // human display label
}

// SAML encapsulates the runtime state for one configured SAML IdP.
// Build via NewSAML; mount its handlers on the chi router with Mount.
type SAML struct {
	cfg      SAMLConfig
	mw       *samlsp.Middleware
	users    *Users
	sessions *Sessions
	store    *store.Store
}

// NewSAML parses the IdP cert + the SP keypair and assembles the
// crewjam/saml middleware. Returns a ready-to-mount SAML handler.
func NewSAML(ctx context.Context, cfg SAMLConfig, users *Users, sessions *Sessions, st *store.Store) (*SAML, error) {
	if err := validateSAMLConfig(cfg); err != nil {
		return nil, err
	}
	rootURL, err := url.Parse(strings.TrimRight(cfg.RootURL, "/"))
	if err != nil {
		return nil, fmt.Errorf("saml: parse RootURL: %w", err)
	}
	keypair, err := loadSPKeyPair(cfg)
	if err != nil {
		return nil, err
	}
	rsaKey, ok := keypair.PrivateKey.(*rsa.PrivateKey)
	if !ok {
		return nil, errors.New("saml: SP private key must be RSA")
	}
	idpMeta, err := loadIDPMetadata(ctx, cfg)
	if err != nil {
		return nil, err
	}
	mw, err := samlsp.New(samlsp.Options{
		EntityID:          cfg.EntityID,
		URL:               *rootURL,
		Key:               rsaKey,
		Certificate:       keypair.Leaf,
		IDPMetadata:       idpMeta,
		AllowIDPInitiated: cfg.AllowIDPInitiated,
		SignRequest:       cfg.SignRequests,
	})
	if err != nil {
		return nil, fmt.Errorf("saml: build middleware: %w", err)
	}
	acsURL := rootURL.ResolveReference(&url.URL{Path: "/saml/" + cfg.ID + "/acs"})
	mw.ServiceProvider.AcsURL = *acsURL
	metaURL := rootURL.ResolveReference(&url.URL{Path: "/saml/" + cfg.ID + "/metadata"})
	mw.ServiceProvider.MetadataURL = *metaURL
	if cfg.EntityID == "" {
		mw.ServiceProvider.EntityID = metaURL.String()
	}
	return &SAML{cfg: cfg, mw: mw, users: users, sessions: sessions, store: st}, nil
}

func validateSAMLConfig(cfg SAMLConfig) error {
	if cfg.ID == "" || cfg.RootURL == "" || cfg.EntryPoint == "" {
		return errors.New("saml: ID, RootURL, EntryPoint required")
	}
	if cfg.IDPMetadataXML == "" && cfg.IDPCertPEM == "" {
		return errors.New("saml: IDPMetadataXML or IDPCertPEM required")
	}
	if cfg.SPCertPEM == "" || cfg.SPKeyPEM == "" {
		return errors.New("saml: SPCertPEM + SPKeyPEM required (generate a self-signed pair)")
	}
	return nil
}

func loadSPKeyPair(cfg SAMLConfig) (tls.Certificate, error) {
	keypair, err := tls.X509KeyPair([]byte(cfg.SPCertPEM), []byte(cfg.SPKeyPEM))
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("saml: SP keypair: %w", err)
	}
	if keypair.Leaf == nil {
		leaf, err := x509.ParseCertificate(keypair.Certificate[0])
		if err != nil {
			return tls.Certificate{}, fmt.Errorf("saml: parse SP leaf cert: %w", err)
		}
		keypair.Leaf = leaf
	}
	return keypair, nil
}

// Config returns the SAMLConfig the handler was constructed with;
// useful for /settings to surface what's configured.
func (s *SAML) Config() SAMLConfig { return s.cfg }

// Button returns the /login-page projection of this connection.
func (s *SAML) Button() SAMLProviderButton {
	label := s.cfg.Label
	if label == "" {
		label = "Sign in with " + s.cfg.ID
	}
	return SAMLProviderButton{ID: s.cfg.ID, Label: label}
}

// Mount wires the per-IdP routes under /saml/{id}/{login,acs,metadata}.
func (s *SAML) Mount(r chi.Router) {
	r.Get("/saml/"+s.cfg.ID+"/login", s.loginHandler)
	r.Post("/saml/"+s.cfg.ID+"/acs", s.acsHandler)
	r.Get("/saml/"+s.cfg.ID+"/metadata", s.metadataHandler)
}

// loginHandler kicks off the SP-initiated flow: generates a
// RelayState-bound AuthnRequest and redirects the browser to the IdP's
// SingleSignOnService URL.
func (s *SAML) loginHandler(w http.ResponseWriter, r *http.Request) {
	s.mw.HandleStartAuthFlow(w, r)
}

// metadataHandler emits the SP metadata XML the operator pastes into
// the IdP.
func (s *SAML) metadataHandler(w http.ResponseWriter, r *http.Request) {
	s.mw.ServeMetadata(w, r)
}

// acsHandler accepts the IdP's POSTed SAMLResponse, verifies it via
// crewjam/saml's middleware, extracts the NameID + attributes, and
// issues a local session.
func (s *SAML) acsHandler(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "saml: parse form: "+err.Error(), http.StatusBadRequest)
		return
	}
	assertion, err := s.mw.ServiceProvider.ParseResponse(r, possibleRequestIDs(r))
	if err != nil {
		http.Error(w, "saml: parse response: "+err.Error(), http.StatusForbidden)
		return
	}
	email, display := extractAssertionIdentity(assertion)
	if email == "" {
		http.Error(w, "saml: assertion missing email / NameID", http.StatusForbidden)
		return
	}
	ctx := r.Context()
	user, err := s.users.ByEmail(ctx, email)
	if errors.Is(err, ErrUserNotFound) {
		// Auto-provision a local row for the SAML-only account.
		user, err = s.users.Create(ctx, email, display, randomPassword(), false)
		if err != nil {
			http.Error(w, "saml: provision user: "+err.Error(), http.StatusInternalServerError)
			return
		}
	} else if err != nil {
		http.Error(w, "saml: user lookup: "+err.Error(), http.StatusInternalServerError)
		return
	}
	sess, err := s.sessions.Create(ctx, user.ID, r.UserAgent(), clientIP(r))
	if err != nil {
		http.Error(w, "saml: create session: "+err.Error(), http.StatusInternalServerError)
		return
	}
	s.sessions.SetCookies(w, sess)
	_ = s.users.TouchLastLogin(ctx, user.ID)
	http.Redirect(w, r, "/", http.StatusSeeOther)
}

// possibleRequestIDs derives the RequestID list crewjam/saml verifies
// against. For IdP-initiated flows we pass nil; for SP-initiated the
// middleware stashed a tracked-request cookie that already encodes the
// RequestID, so the middleware finds it without our help.
func possibleRequestIDs(r *http.Request) []string {
	_ = r
	return nil
}

// extractAssertionIdentity pulls the email + display name out of a
// verified assertion. Tries the canonical attribute names IdPs emit,
// then falls back to the NameID itself.
func extractAssertionIdentity(a *saml.Assertion) (email, display string) {
	if a == nil || a.Subject == nil || a.Subject.NameID == nil {
		return "", ""
	}
	for _, stmt := range a.AttributeStatements {
		for _, attr := range stmt.Attributes {
			if len(attr.Values) == 0 {
				continue
			}
			switch attr.Name {
			case "email", "Email",
				"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":
				email = attr.Values[0].Value
			case "displayName", "DisplayName", "name",
				"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name":
				display = attr.Values[0].Value
			}
		}
	}
	if email == "" {
		// NameID is by spec an email per the EmailAddress format; trust
		// it as the canonical identifier.
		email = a.Subject.NameID.Value
	}
	if display == "" {
		display = email
	}
	return email, display
}

// loadIDPMetadata fetches/parses the IdP's metadata. Prefers the
// inline XML; falls back to a synthesized metadata blob built from the
// raw cert PEM + EntryPoint URL.
func loadIDPMetadata(ctx context.Context, cfg SAMLConfig) (*saml.EntityDescriptor, error) {
	_ = ctx
	if cfg.IDPMetadataXML != "" {
		ed, err := samlsp.ParseMetadata([]byte(cfg.IDPMetadataXML))
		if err != nil {
			return nil, fmt.Errorf("saml: parse IDPMetadataXML: %w", err)
		}
		return ed, nil
	}
	block, _ := pem.Decode([]byte(cfg.IDPCertPEM))
	if block == nil {
		return nil, errors.New("saml: IDPCertPEM is not valid PEM")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("saml: parse IDPCertPEM: %w", err)
	}
	return &saml.EntityDescriptor{
		EntityID: cfg.EntryPoint,
		IDPSSODescriptors: []saml.IDPSSODescriptor{{
			SSODescriptor: saml.SSODescriptor{
				RoleDescriptor: saml.RoleDescriptor{
					KeyDescriptors: []saml.KeyDescriptor{{
						Use: "signing",
						KeyInfo: saml.KeyInfo{
							X509Data: saml.X509Data{
								X509Certificates: []saml.X509Certificate{{
									Data: encodeCertNoHeaders(cert),
								}},
							},
						},
					}},
				},
			},
			SingleSignOnServices: []saml.Endpoint{{
				Binding:  saml.HTTPRedirectBinding,
				Location: cfg.EntryPoint,
			}},
		}},
	}, nil
}

// encodeCertNoHeaders returns the raw base64-DER of cert (no PEM
// header lines) — the format crewjam/saml expects in X509Certificates.
func encodeCertNoHeaders(cert *x509.Certificate) string {
	pemBytes := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw})
	out := string(pemBytes)
	out = strings.ReplaceAll(out, "-----BEGIN CERTIFICATE-----\n", "")
	out = strings.ReplaceAll(out, "\n-----END CERTIFICATE-----\n", "")
	out = strings.ReplaceAll(out, "\n", "")
	return out
}

// randomPassword returns a 32-byte hex-encoded string used as the
// PasswordHash basis for SAML-auto-provisioned accounts. The user
// can't log in with this — there's no path to discover it. SAML
// remains the only auth channel for that account.
func randomPassword() string {
	tok, err := randomToken(16)
	if err != nil {
		return "saml-auto-" + time.Now().UTC().Format(time.RFC3339Nano)
	}
	return "saml-auto-" + tok
}
