// Command genapi enumerates the exported API surface of
// pkg/compliancekit and writes (or diffs) the canonical snapshot at
// pkg/compliancekit/api.txt.
//
// Run:
//
//	go run ./cmd/genapi              # regenerate pkg/compliancekit/api.txt
//	go run ./cmd/genapi -check       # exit 1 if the snapshot is stale
//	go run ./cmd/genapi -out=foo.txt # write somewhere else
//
// The -check mode is the v1.0 CI gate. It is what turns "we promise
// API stability" into a machine-enforced invariant: a maintainer can
// only widen, narrow, or rename the public contract by committing the
// regenerated api.txt in the same PR, which makes every contract
// change visible at review time.
//
// Why a separate tool rather than a //go:generate inside
// pkg/compliancekit? The package is intentionally tiny and self-
// contained at v1.0; pulling a generator into it would bloat the
// import graph for embedders. Keeping the tool under cmd/ also
// mirrors the gencheckdocs pattern already established for the
// checks catalog.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// pkgDir is the on-disk location of the v1.0 public package.
const pkgDir = "pkg/compliancekit"

// defaultOut is where the canonical snapshot lives. -check reads from
// here; the default write target is also here.
const defaultOut = "pkg/compliancekit/api.txt"

// header is the leading comment block preserved verbatim across
// regenerations so the file's purpose is discoverable without
// hunting the git log.
const header = `# Public API surface of pkg/compliancekit, regenerated by cmd/genapi.
#
# Adding, renaming, or removing an exported identifier is a SemVer-
# significant change. The CI gate (` + "`go run ./cmd/genapi -check`" + `) fails
# the build when this file drifts from the package source, so a
# contract change cannot land without an explicit, reviewed diff to
# this file.
#
# v1.0 baseline lands incrementally across the phase commits — the
# initial Phase 0 commit ships the gate and an empty contract;
# subsequent phases promote one type family at a time.
`

func main() {
	var (
		outPath = flag.String("out", defaultOut, "output path for the snapshot")
		check   = flag.Bool("check", false, "exit 1 if the snapshot at -out is stale")
	)
	flag.Parse()

	lines, err := scanPackage(pkgDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genapi: scan %s: %v\n", pkgDir, err)
		os.Exit(2)
	}
	sort.Strings(lines)

	var buf bytes.Buffer
	buf.WriteString(header)
	if len(lines) > 0 {
		buf.WriteByte('\n')
		for _, l := range lines {
			buf.WriteString(l)
			buf.WriteByte('\n')
		}
	}
	want := buf.Bytes()

	if *check {
		got, err := os.ReadFile(*outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "genapi: read %s: %v\n", *outPath, err)
			os.Exit(2)
		}
		if !bytes.Equal(got, want) {
			fmt.Fprintf(os.Stderr,
				"genapi: %s is stale — regenerate via `go run ./cmd/genapi`\n",
				*outPath)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(*outPath, want, 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "genapi: write %s: %v\n", *outPath, err)
		os.Exit(2)
	}
}

// scanPackage walks the non-test Go files in dir and returns one
// canonical-form line per exported identifier. Sorted later by the
// caller so the snapshot is byte-stable across re-runs and across
// platforms.
func scanPackage(dir string) ([]string, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}

	var out []string
	for _, pkg := range pkgs {
		// Iterate files in lexical order for deterministic output even
		// before the final sort, mostly so a stack trace from a panic
		// inside one of the formatters points at the same file every
		// time.
		paths := make([]string, 0, len(pkg.Files))
		for p := range pkg.Files {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			for _, decl := range pkg.Files[p].Decls {
				out = append(out, declLines(fset, filepath.Base(p), decl)...)
			}
		}
	}
	return out, nil
}

// declLines turns one top-level declaration into zero or more
// snapshot lines. Unexported identifiers and blank-name imports are
// skipped silently.
func declLines(fset *token.FileSet, _ string, decl ast.Decl) []string {
	switch d := decl.(type) {
	case *ast.GenDecl:
		return genDeclLines(fset, d)
	case *ast.FuncDecl:
		if d.Recv != nil {
			return methodLines(fset, d)
		}
		return funcLines(fset, d)
	}
	return nil
}

// genDeclLines handles TYPE / CONST / VAR blocks. IMPORT is ignored.
func genDeclLines(fset *token.FileSet, d *ast.GenDecl) []string {
	var out []string
	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.TypeSpec:
			if !s.Name.IsExported() {
				continue
			}
			out = append(out, formatType(fset, s))
		case *ast.ValueSpec:
			kw := "var"
			if d.Tok == token.CONST {
				kw = "const"
			}
			for i, name := range s.Names {
				if !name.IsExported() {
					continue
				}
				out = append(out, formatValue(fset, kw, name.Name, s, i))
			}
		}
	}
	return out
}

// formatType produces e.g. "type Severity int", "type Finding struct",
// "type Reporter interface", or "type CheckFunc = func(...) (...)".
// Type aliases (Assign != 0) emit the full RHS so the snapshot
// captures the aliased target. Structs and interfaces collapse to the
// keyword alone; field-level changes are surface-level only when an
// exported field's signature is what changed, which subsequent
// per-field lines (if we ever add them) would track. v1.0 keeps the
// snapshot at the type-shape level — fine-grained field surveillance
// is left for v1.1+ if it earns its keep.
func formatType(fset *token.FileSet, s *ast.TypeSpec) string {
	if s.Assign != 0 {
		return fmt.Sprintf("type %s = %s", s.Name.Name, exprString(fset, s.Type))
	}
	switch s.Type.(type) {
	case *ast.StructType:
		return fmt.Sprintf("type %s struct", s.Name.Name)
	case *ast.InterfaceType:
		return fmt.Sprintf("type %s interface", s.Name.Name)
	}
	return fmt.Sprintf("type %s %s", s.Name.Name, exprString(fset, s.Type))
}

// formatValue produces "const X T", "const X = value" (when the
// declared type is implicit), or "var X T". The expression form is
// preserved verbatim when no explicit type is set so the snapshot
// catches a literal value change (think: SeverityHigh = 5 → 6).
func formatValue(fset *token.FileSet, kw, name string, s *ast.ValueSpec, i int) string {
	if s.Type != nil {
		return fmt.Sprintf("%s %s %s", kw, name, exprString(fset, s.Type))
	}
	if i < len(s.Values) {
		return fmt.Sprintf("%s %s = %s", kw, name, exprString(fset, s.Values[i]))
	}
	return fmt.Sprintf("%s %s", kw, name)
}

// funcLines produces "func Name(args) results" for one exported
// top-level function. Unexported funcs return nil.
func funcLines(fset *token.FileSet, d *ast.FuncDecl) []string {
	if !d.Name.IsExported() {
		return nil
	}
	return []string{fmt.Sprintf("func %s%s", d.Name.Name, signatureString(fset, d.Type))}
}

// methodLines produces "method (T) Name(args) results" for exported
// methods. Unexported methods (and methods on unexported receivers)
// return nil.
func methodLines(fset *token.FileSet, d *ast.FuncDecl) []string {
	if !d.Name.IsExported() {
		return nil
	}
	if len(d.Recv.List) == 0 {
		return nil
	}
	recv := exprString(fset, d.Recv.List[0].Type)
	// Receiver of (*T) — strip the leading * for "T" identification,
	// then report which is which.
	bare := strings.TrimPrefix(recv, "*")
	if !ast.IsExported(bare) {
		return nil
	}
	return []string{fmt.Sprintf("method (%s) %s%s", recv, d.Name.Name, signatureString(fset, d.Type))}
}

// signatureString produces the "(args) result" tail of a function
// signature, e.g. "(s string) (Severity, error)". No leading
// space — caller decides the gap.
func signatureString(fset *token.FileSet, ft *ast.FuncType) string {
	var b strings.Builder
	b.WriteByte('(')
	b.WriteString(fieldListString(fset, ft.Params))
	b.WriteByte(')')
	if ft.Results != nil && len(ft.Results.List) > 0 {
		r := fieldListString(fset, ft.Results)
		// A single unnamed result drops the parens.
		if len(ft.Results.List) == 1 && len(ft.Results.List[0].Names) == 0 {
			b.WriteByte(' ')
			b.WriteString(r)
		} else {
			b.WriteString(" (")
			b.WriteString(r)
			b.WriteByte(')')
		}
	}
	return b.String()
}

// fieldListString renders a parameter or result list — names if any,
// then the type. Comma-separated. Empty list -> empty string.
func fieldListString(fset *token.FileSet, fl *ast.FieldList) string {
	if fl == nil {
		return ""
	}
	parts := make([]string, 0, len(fl.List))
	for _, f := range fl.List {
		ts := exprString(fset, f.Type)
		if len(f.Names) == 0 {
			parts = append(parts, ts)
			continue
		}
		names := make([]string, 0, len(f.Names))
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
		parts = append(parts, strings.Join(names, ", ")+" "+ts)
	}
	return strings.Join(parts, ", ")
}

// exprString formats an arbitrary AST expression back to source via
// go/printer. Used everywhere a type or value expression needs to
// appear in the snapshot.
func exprString(fset *token.FileSet, e ast.Expr) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, fset, e)
	return buf.String()
}
