package evidence

import (
	"fmt"
	"io"
	"os"
	"sort"
	"time"

	"github.com/darpanzope/compliancekit/internal/core"
	"github.com/darpanzope/compliancekit/internal/frameworks"
)

// writeControlMarkdown emits <control-dir>/control.md -- the auditor-
// facing summary for one (framework, control) pair. The Markdown is
// designed to be readable in plain text and renders cleanly in
// GitHub, Notion, and Word.
//
// Sections in order:
//
//	# <control id> -- <control name>
//	(framework / period / generated metadata)
//
//	## Control statement
//	(framework description of the control, lifted from the yaml)
//
//	## Coverage summary
//	(per-check pass/fail/skip/error tallies)
//
//	## Findings
//	(per-finding bullet: status icon, severity, resource, message)
//
//	## Notes
//	(generated-by line; redaction disclosure if applicable)
func writeControlMarkdown(path string, c ControlRef, opts Options) error {
	// G304: path is built from operator-controlled OutDir plus slugs
	// we generated.
	//nolint:gosec // operator-controlled output path
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()
	renderControlMarkdown(f, c, opts)
	return nil
}

// renderControlMarkdown writes the Markdown body to w. Split from
// writeControlMarkdown so tests can render to a buffer without
// touching disk. fmt.Fprint failures on an io.Writer are surfaced as
// the writer's own error on the next call; the public-facing
// error-return surface is at writeControlMarkdown, which already
// handles file-open failure.
func renderControlMarkdown(w io.Writer, c ControlRef, opts Options) {
	desc := lookupControlDescription(c.FrameworkID, c.ControlID)

	fmt.Fprintf(w, "# %s — %s\n\n", c.ControlID, c.ControlName)
	fmt.Fprintf(w, "- **Framework:** %s (`%s`)\n", c.FrameworkName, c.FrameworkID)
	fmt.Fprintf(w, "- **Period:** %s\n", opts.Period)
	fmt.Fprintf(w, "- **Generated:** %s\n", opts.Generated.Format(time.RFC3339))
	fmt.Fprintln(w)

	if desc != "" {
		fmt.Fprintln(w, "## Control statement")
		fmt.Fprintln(w)
		fmt.Fprintln(w, desc)
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "## Coverage summary")
	fmt.Fprintln(w)
	writeCoverageTable(w, c.Findings)
	fmt.Fprintln(w)

	fmt.Fprintln(w, "## Findings")
	fmt.Fprintln(w)
	if len(c.Findings) == 0 {
		fmt.Fprintln(w, "_No findings recorded for this control._")
	} else {
		writeFindingsList(w, c.Findings)
	}
	fmt.Fprintln(w)

	fmt.Fprintln(w, "## Notes")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "- Generated by compliancekit. See `findings.json` in this directory for the machine-readable form.")
	if !opts.IncludeRaw {
		fmt.Fprintln(w, "- Sensitive tokens in finding messages have been redacted. Re-run with `--include-raw` for the unredacted pack.")
	}
}

// writeCoverageTable renders a per-check breakdown as a GitHub-flavored
// Markdown table. One row per check_id present in the findings slice;
// columns are pass/fail/skip/error counts so the auditor can see at a
// glance which checks are exercising this control.
func writeCoverageTable(w io.Writer, findings []core.Finding) {
	type row struct {
		CheckID                       string
		Title                         string
		Pass, Fail, Skip, Errored, NA int
	}
	byCheck := map[string]*row{}
	for _, f := range findings {
		r, ok := byCheck[f.CheckID]
		if !ok {
			r = &row{CheckID: f.CheckID}
			if chk, found := core.LookupCheck(f.CheckID); found {
				r.Title = chk.Title
			}
			byCheck[f.CheckID] = r
		}
		switch f.Status {
		case core.StatusPass:
			r.Pass++
		case core.StatusFail:
			r.Fail++
		case core.StatusSkip:
			r.Skip++
		case core.StatusError:
			r.Errored++
		default:
			r.NA++
		}
	}
	rows := make([]*row, 0, len(byCheck))
	for _, r := range byCheck {
		rows = append(rows, r)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].CheckID < rows[j].CheckID })

	fmt.Fprintln(w, "| Check | Title | Pass | Fail | Skip | Error |")
	fmt.Fprintln(w, "|---|---|---:|---:|---:|---:|")
	for _, r := range rows {
		fmt.Fprintf(w, "| `%s` | %s | %d | %d | %d | %d |\n",
			r.CheckID, escapeTable(r.Title), r.Pass, r.Fail, r.Skip, r.Errored)
	}
}

// writeFindingsList renders one bullet per finding -- status icon for
// the auditor to scan, severity in brackets, resource name in code
// font, then the message.
//
// The icons are unicode glyphs (✅ pass, ❌ fail, ⏭ skip,
// ⚠️ error) chosen for legibility in dark + light themes.
func writeFindingsList(w io.Writer, findings []core.Finding) {
	for _, f := range findings {
		fmt.Fprintf(w, "- %s [%s] `%s` — %s\n",
			statusIcon(f.Status), f.Severity.String(), f.Resource.Name, f.Message)
	}
}

func statusIcon(s core.Status) string {
	switch s {
	case core.StatusPass:
		return "✅"
	case core.StatusFail:
		return "❌"
	case core.StatusSkip:
		return "⏭"
	case core.StatusError:
		return "⚠️"
	}
	return "·"
}

// escapeTable masks the few characters that would break GitHub
// Markdown table rendering. We only strip pipe and newline; backslashes
// and other punctuation render fine inside a table cell.
func escapeTable(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range s {
		switch r {
		case '|':
			out = append(out, '\\', '|')
		case '\n', '\r':
			out = append(out, ' ')
		default:
			out = append(out, r)
		}
	}
	return string(out)
}

// lookupControlDescription pulls the description field for the given
// control out of the framework catalog. Returns "" when either the
// framework or the control is unknown so callers can branch on the
// empty string rather than threading an error.
func lookupControlDescription(fwID, ctrlID string) string {
	fw, ok := frameworks.Get(fwID)
	if !ok {
		return ""
	}
	ctrl, ok := fw.Controls[ctrlID]
	if !ok {
		return ""
	}
	return ctrl.Description
}
