package cli

// v1.13 phase 1 — `compliancekit checks new <id>` plugin scaffolder.
//
// Generates a starter plugin directory with a manifest, a Rego check
// pack (the default — no Go subprocess required), a test fixture, and
// a README. Operators run:
//
//   compliancekit checks new my-aws-iam-check
//   compliancekit plugins install ./my-aws-iam-check
//
// and have a working plugin in two commands.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/darpanzope/compliancekit/pkg/compliancekit/plugin"
)

// idPattern guards the user-provided plugin ID so the scaffolder
// can't be coerced into writing outside the target directory.
// Lowercase letters, digits, dots, and hyphens; 3-60 chars.
var idPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9.\-]{1,58}[a-z0-9]$`)

func newChecksNewCmd() *cobra.Command {
	var (
		outputDir string
		kind      string
		goPlugin  bool
		author    string
	)
	cmd := &cobra.Command{
		Use:   "new <id>",
		Short: "Scaffold a starter plugin directory",
		Long: `Generate a runnable plugin skeleton with a manifest, a sample
check (Rego by default; Go subprocess with --go), a test fixture, and
a README.

The output directory is named after <id> and lands under --output
(default: current working directory). The directory is ready to
install:

  compliancekit checks new aws-iam-mfa-strict
  compliancekit plugins install ./aws-iam-mfa-strict

<id> must be lowercase + 3-60 chars + start/end alphanumeric.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id := args[0]
			if !idPattern.MatchString(id) {
				return NewExitCode(2, "invalid plugin id %q: must match %s", id, idPattern.String())
			}
			knownKind := plugin.Kind(kind)
			if kind == "" {
				knownKind = plugin.KindCheck
			}
			if !isKnownPluginKind(knownKind) {
				return NewExitCode(2, "invalid --kind %q: must be one of check/provider/notifier/reporter", kind)
			}
			if outputDir == "" {
				wd, err := os.Getwd()
				if err != nil {
					return fmt.Errorf("getwd: %w", err)
				}
				outputDir = wd
			}
			dest := filepath.Join(outputDir, id)
			if _, err := os.Stat(dest); err == nil {
				return NewExitCode(2, "destination %s already exists", dest)
			}
			if err := os.MkdirAll(dest, 0o750); err != nil {
				return fmt.Errorf("mkdir %s: %w", dest, err)
			}
			if err := scaffold(dest, id, knownKind, goPlugin, author); err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "scaffolded %s plugin at %s\n", knownKind, dest)
			fmt.Fprintln(cmd.OutOrStdout(), "next:")
			fmt.Fprintf(cmd.OutOrStdout(), "  compliancekit plugins install %s\n", dest)
			return nil
		},
	}
	cmd.Flags().StringVar(&outputDir, "output", "", "parent directory the plugin folder is written under (default: cwd)")
	cmd.Flags().StringVar(&kind, "kind", string(plugin.KindCheck), "plugin kind: check / provider / notifier / reporter")
	cmd.Flags().BoolVar(&goPlugin, "go", false, "scaffold a Go subprocess plugin (default: Rego-only pack)")
	cmd.Flags().StringVar(&author, "author", "", "manifest.author value (defaults to $USER)")
	return cmd
}

func isKnownPluginKind(k plugin.Kind) bool {
	for _, known := range plugin.AllKinds {
		if known == k {
			return true
		}
	}
	return false
}

// scaffold writes the manifest + sample check + test + README into
// dest. The shape mirrors what `plugins install` expects so the round
// trip works out of the box.
func scaffold(dest, id string, kind plugin.Kind, goPlugin bool, author string) error {
	if author == "" {
		author = strings.TrimSpace(os.Getenv("USER"))
		if author == "" {
			author = "anonymous"
		}
	}
	manifestBody := buildManifest(id, kind, goPlugin, author)
	if err := os.WriteFile(filepath.Join(dest, "manifest.yaml"), []byte(manifestBody), 0o600); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}
	readmeBody := buildReadme(id, kind, goPlugin, author)
	if err := os.WriteFile(filepath.Join(dest, "README.md"), []byte(readmeBody), 0o600); err != nil {
		return fmt.Errorf("write readme: %w", err)
	}
	if goPlugin {
		if err := scaffoldGoPlugin(dest, id); err != nil {
			return err
		}
	} else {
		if err := scaffoldRegoPlugin(dest, id); err != nil {
			return err
		}
	}
	return nil
}

func buildManifest(id string, kind plugin.Kind, goPlugin bool, author string) string {
	var entry string
	var rego string
	if goPlugin {
		entry = "entrypoint: ./bin/" + id + "\n"
	} else {
		rego = "rego_packs:\n  - rego/" + id + ".rego\n"
	}
	now := time.Now().UTC().Format(time.RFC3339)
	return fmt.Sprintf(`# Generated by `+"`compliancekit checks new %s`"+` at %s.
apiVersion: %s
name: %s
version: v0.1.0
author: %s
license: Apache-2.0
description: Starter %s plugin generated by the scaffolder.

kinds:
  - %s

required_scopes:
  - scans:read

declared_egress: []

%s%s`, id, now, plugin.APIVersion, id, author, kind, kind, entry, rego)
}

func buildReadme(id string, kind plugin.Kind, goPlugin bool, author string) string {
	mode := "Rego-only"
	if goPlugin {
		mode = "Go subprocess"
	}
	return fmt.Sprintf("# %s\n\nA %s compliancekit %s plugin scaffolded by `compliancekit checks new`.\n\n"+
		"## Develop\n\n"+
		"Edit `manifest.yaml` to refine the metadata, then iterate on the check body:\n\n"+
		"- Rego: `rego/%s.rego`\n"+
		"- Go subprocess: `cmd/%s/main.go` + `go build -o bin/%s ./cmd/%s`\n\n"+
		"## Install\n\n"+
		"```\ncompliancekit plugins install ./%s\n```\n\n"+
		"## Sign (production)\n\n"+
		"```\ncosign sign-blob --bundle %s.cosign.bundle manifest.yaml\n```\n\n"+
		"Author: %s\n",
		id, mode, kind, id, id, id, id, id, id, author)
}

func scaffoldRegoPlugin(dest, id string) error {
	regoDir := filepath.Join(dest, "rego")
	if err := os.MkdirAll(regoDir, 0o750); err != nil {
		return fmt.Errorf("mkdir rego: %w", err)
	}
	body := fmt.Sprintf(`# Starter Rego pack for the %s plugin.
#
# Replace the violation rule with whatever predicate the operator
# wants enforced. Inputs available:
#   input.resource       — the current resource under evaluation
#   input.findings       — sibling findings from the scan
#
# See https://www.openpolicyagent.org/docs/policy-language for the
# Rego language reference.

package compliancekit.checks.%s

# Example: flag every resource whose attrs.example is missing.
violation[result] {
    not input.resource.attrs.example
    result := {
        "message": "resource missing required attrs.example",
        "severity": "medium",
    }
}
`, id, regoPackageID(id))
	return os.WriteFile(filepath.Join(regoDir, id+".rego"), []byte(body), 0o600)
}

// regoPackageID converts a plugin id like "aws-iam-mfa" into a Rego-
// safe package suffix "aws_iam_mfa".
func regoPackageID(id string) string {
	return strings.NewReplacer("-", "_", ".", "_").Replace(id)
}

func scaffoldGoPlugin(dest, id string) error {
	cmdDir := filepath.Join(dest, "cmd", id)
	if err := os.MkdirAll(cmdDir, 0o750); err != nil {
		return fmt.Errorf("mkdir cmd: %w", err)
	}
	main := fmt.Sprintf(`// %s — compliancekit plugin subprocess.
//
// Built artifact lands at bin/%s; the daemon execs it with the
// hashicorp/go-plugin handshake. Replace the body with the actual
// check logic.
package main

import (
	"fmt"
	"os"
)

func main() {
	// TODO(operator): implement the hashicorp/go-plugin handshake
	// + dispatch the check kind requested by the daemon. The v1.13
	// daemon hands the plugin a JSON ResourceGraph on stdin and
	// expects a JSON []Finding on stdout.
	fmt.Fprintln(os.Stderr, "%s plugin starting (replace stub)")
}
`, id, id, id)
	return os.WriteFile(filepath.Join(cmdDir, "main.go"), []byte(main), 0o600)
}
