apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daemon
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: compliancekit.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: daemon
                port:
                  number: 80
  tls:
    - secretName: compliancekit-tls
      hosts:
        - compliancekit.example.com
