package ui

// v1.4 Phase 7 — CI workflow generator.
//
// /export/ci renders downloadable CI workflow files matching the
// operator's current configuration. Three flavors: GitHub Actions
// (.github/workflows/compliance.yaml), GitLab CI (.gitlab-ci.yml),
// and CircleCI (.circleci/config.yml).
//
// Each flavor includes:
//   - schedule + push + PR triggers
//   - the right secret references for each enabled provider
//   - evidence-pack artifact upload step
//   - OIDC setup hints in comments
//
// Generator state lives in DB (providers, checks_state,
// framework_tailoring) — same source the Phase 6 YAML preview reads
// from.

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"sort"
	"text/template"

	"github.com/go-chi/chi/v5"
)

// ciFlavor is a discriminator for which template to render.
type ciFlavor string

const (
	ciGitHub   ciFlavor = "github"
	ciGitLab   ciFlavor = "gitlab"
	ciCircleCI ciFlavor = "circleci"
)

// ciContext is the value handed to the CI templates. Providers are
// in stable order so the generated file is reproducible.
type ciContext struct {
	Providers      []ciProvider
	Frameworks     []string
	HasAuditTokens bool // true if at least one configured provider needs a secret
}

// ciProvider is the per-provider entry in the CI render — id +
// secret name + env var name. Secret names follow the convention
// "<PROVIDERID>_TOKEN" so operators paste once in CI settings.
type ciProvider struct {
	ID        string
	Name      string
	SecretRef string // e.g. "${{ secrets.DIGITALOCEAN_TOKEN }}"
	EnvVar    string // e.g. "DIGITALOCEAN_TOKEN"
}

// buildCIContext walks the providers table for every enabled row and
// stamps the secret/env shape per provider.
func (u *UI) buildCIContext(ctx context.Context) (ciContext, error) {
	rows, err := u.loadProviderRows(ctx)
	if err != nil {
		return ciContext{}, err
	}
	out := ciContext{}
	for _, r := range rows {
		if !r.Configured || !r.Enabled {
			continue
		}
		env := envVarFor(r.ID)
		out.Providers = append(out.Providers, ciProvider{
			ID:        r.ID,
			Name:      r.Name,
			SecretRef: "${{ secrets." + env + " }}",
			EnvVar:    env,
		})
	}
	if len(out.Providers) > 0 {
		out.HasAuditTokens = true
	}
	sort.Slice(out.Providers, func(i, j int) bool { return out.Providers[i].ID < out.Providers[j].ID })

	// Frameworks from the catalog with at least one tailoring row OR
	// every shipping framework if the operator hasn't tailored — the
	// CI runs the full set by default.
	fwRows, _ := u.allTailoringDecisions(ctx)
	if len(fwRows) > 0 {
		for fw := range fwRows {
			out.Frameworks = append(out.Frameworks, fw)
		}
	}
	sort.Strings(out.Frameworks)
	return out, nil
}

// envVarFor maps a provider id to the canonical secret name used
// across all three CI flavors. Keeps the operator's "paste-once"
// experience consistent.
func envVarFor(providerID string) string {
	switch providerID {
	case "digitalocean":
		return "DIGITALOCEAN_TOKEN"
	case "aws":
		return "AWS_ROLE_ARN"
	case "gcp":
		return "GOOGLE_APPLICATION_CREDENTIALS_JSON"
	case "hetzner":
		return "HCLOUD_TOKEN"
	case "kubernetes":
		return "KUBECONFIG"
	case "linux":
		return "LINUX_SSH_KEY"
	default:
		return "COMPLIANCEKIT_TOKEN"
	}
}

// ciTemplates is parsed once at init. Each template defines the full
// file the operator downloads.
var ciTemplates = template.Must(template.New("ci").Parse(`
{{ define "github" -}}
# .github/workflows/compliance.yaml — generated by compliancekit Studio
#
# This workflow runs on every PR + every push to main + on a weekly
# schedule. The evidence-pack artifact is uploaded after every run so
# auditors can review what was scanned and what failed.
#
# Secrets to set in GitHub → Settings → Secrets and variables → Actions:
{{- range .Providers }}
#   {{ .EnvVar }} — {{ .Name }} {{ if eq .ID "aws" }}(prefer OIDC: github.com/aws-actions/configure-aws-credentials){{ end }}
{{- end }}

name: compliancekit scan

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 4 * * 1"   # Mondays 04:00 UTC

permissions:
  contents: read
  id-token: write          # for AWS / GCP OIDC
  pull-requests: write     # for PR comments
  security-events: write   # for SARIF uploads

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run compliancekit
        uses: darpanzope/compliancekit-action@v1
        env:
{{- range .Providers }}
          {{ .EnvVar }}: {{ .SecretRef }}
{{- end }}

      - name: Upload evidence pack
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compliance-evidence
          path: ./.compliancekit/
          retention-days: 90
{{- end }}

{{ define "gitlab" -}}
# .gitlab-ci.yml — generated by compliancekit Studio
#
# Add the following project-level variables (Settings → CI/CD →
# Variables, masked + protected):
{{- range .Providers }}
#   {{ .EnvVar }} — {{ .Name }}
{{- end }}

stages:
  - compliance

compliancekit_scan:
  stage: compliance
  image: ghcr.io/darpanzope/compliancekit:latest
  variables:
    GIT_DEPTH: 1
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - compliancekit scan
  artifacts:
    name: compliance-evidence
    when: always
    expire_in: 90 days
    paths:
      - .compliancekit/
{{- end }}

{{ define "circleci" -}}
# .circleci/config.yml — generated by compliancekit Studio
#
# Context names assumed (CircleCI → Organization Settings →
# Contexts → "compliancekit"):
{{- range .Providers }}
#   {{ .EnvVar }} — {{ .Name }}
{{- end }}

version: 2.1

jobs:
  compliancekit-scan:
    docker:
      - image: ghcr.io/darpanzope/compliancekit:latest
    steps:
      - checkout
      - run:
          name: Scan
          command: compliancekit scan
      - store_artifacts:
          path: .compliancekit
          destination: compliance-evidence

workflows:
  version: 2
  on_pr_and_schedule:
    jobs:
      - compliancekit-scan:
          context: compliancekit
{{- end }}
`))

// renderCI returns the rendered file body for the given flavor.
func (u *UI) renderCI(ctx context.Context, flavor ciFlavor) (string, error) {
	cictx, err := u.buildCIContext(ctx)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := ciTemplates.ExecuteTemplate(&buf, string(flavor), cictx); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// mountCIRoutes registers the Phase 7 endpoints.
func (u *UI) mountCIRoutes(r chi.Router) {
	r.Get("/export/ci", u.exportCIView)
	r.Get("/export/ci/{flavor}/raw", u.exportCIRaw)
	r.Get("/export/ci/{flavor}/download", u.exportCIDownload)
}

// exportCIView renders the tabbed UI with all three flavors visible.
func (u *UI) exportCIView(w http.ResponseWriter, r *http.Request) {
	gh, err := u.renderCI(r.Context(), ciGitHub)
	if err != nil {
		u.fail(w, "render github: "+err.Error())
		return
	}
	gl, err := u.renderCI(r.Context(), ciGitLab)
	if err != nil {
		u.fail(w, "render gitlab: "+err.Error())
		return
	}
	cc, err := u.renderCI(r.Context(), ciCircleCI)
	if err != nil {
		u.fail(w, "render circleci: "+err.Error())
		return
	}
	v := struct {
		View
		GitHub   string
		GitLab   string
		CircleCI string
	}{
		View:     u.viewFor(r, "CI workflows · Export", "settings", View{}),
		GitHub:   gh,
		GitLab:   gl,
		CircleCI: cc,
	}
	u.render(w, "export_ci.html", v)
}

// exportCIRaw returns one flavor as text/plain.
func (u *UI) exportCIRaw(w http.ResponseWriter, r *http.Request) {
	flavor := pathFlavor(r)
	if !validFlavor(flavor) {
		http.NotFound(w, r)
		return
	}
	body, err := u.renderCI(r.Context(), flavor)
	if err != nil {
		http.Error(w, "render: "+err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	fmt.Fprint(w, body)
}

// exportCIDownload returns one flavor as an attachment.
func (u *UI) exportCIDownload(w http.ResponseWriter, r *http.Request) {
	flavor := pathFlavor(r)
	if !validFlavor(flavor) {
		http.NotFound(w, r)
		return
	}
	body, err := u.renderCI(r.Context(), flavor)
	if err != nil {
		http.Error(w, "render: "+err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/yaml; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="`+downloadFilename(flavor)+`"`)
	fmt.Fprint(w, body)
}

func pathFlavor(r *http.Request) ciFlavor {
	return ciFlavor(chi.URLParam(r, "flavor"))
}

func validFlavor(f ciFlavor) bool {
	return f == ciGitHub || f == ciGitLab || f == ciCircleCI
}

func downloadFilename(f ciFlavor) string {
	switch f {
	case ciGitHub:
		return "compliance.yaml"
	case ciGitLab:
		return ".gitlab-ci.yml"
	case ciCircleCI:
		return "config.yml"
	default:
		return "compliancekit-ci.yaml"
	}
}
