package ui

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
)

// TestRenderGeneratedYAML_EmptyDB confirms the empty-state header
// reads "(no providers configured yet)" — a fresh daemon shouldn't
// emit an empty `{}` or a broken-looking file.
func TestRenderGeneratedYAML_EmptyDB(t *testing.T) {
	u, _ := newUIForTests(t)
	body, err := u.renderGeneratedYAML(context.Background())
	if err != nil {
		t.Fatalf("renderGeneratedYAML: %v", err)
	}
	if !strings.Contains(body, "no providers configured yet") {
		t.Errorf("empty body did not flag the unconfigured state:\n%s", body)
	}
	if !strings.HasPrefix(body, "# compliancekit.yaml — generated by the Studio") {
		t.Errorf("missing header comment:\n%s", body[:120])
	}
}

// TestRenderGeneratedYAML_WithProviderAndOverride confirms a
// configured provider + a disabled check + a tailoring exclusion all
// land in the YAML in the expected shape.
func TestRenderGeneratedYAML_WithProviderAndOverride(t *testing.T) {
	ctx := context.Background()
	u, _ := newUIForTests(t)

	// Configure DO with region + services.
	if err := u.upsertProvider(ctx, "digitalocean", "tok_ok", nil); err != nil {
		t.Fatalf("upsertProvider: %v", err)
	}
	cfg := providerConfig{
		Token:    "tok_ok",
		Region:   "fra1, nyc1",
		Services: []string{"droplets", "spaces"},
	}
	if err := u.writeProviderConfig(ctx, "digitalocean", cfg, errKeepExistingStatus); err != nil {
		t.Fatalf("writeProviderConfig: %v", err)
	}

	// Disable a check.
	if err := u.upsertCheckOverride(ctx, "do-spaces-public-acl", false); err != nil {
		t.Fatalf("upsertCheckOverride: %v", err)
	}

	body, err := u.renderGeneratedYAML(ctx)
	if err != nil {
		t.Fatalf("renderGeneratedYAML: %v", err)
	}

	must := []string{
		"providers:",
		"digitalocean:",
		"region: ", // region appears
		"droplets", // service appears
		"checks:",
		"do-spaces-public-acl", // disabled check appears
	}
	for _, m := range must {
		if !strings.Contains(body, m) {
			t.Errorf("missing %q in:\n%s", m, body)
		}
	}
}

// TestYAMLRoutesMounted exercises all three Phase 6 GET routes.
func TestYAMLRoutesMounted(t *testing.T) {
	u, _ := newUIForTests(t)
	r := chi.NewRouter()
	u.mountYAMLRoutes(r)
	for _, path := range []string{"/settings/yaml", "/settings/yaml/raw", "/settings/yaml/download"} {
		req := httptest.NewRequest("GET", path, nil)
		rec := httptest.NewRecorder()
		r.ServeHTTP(rec, req)
		if rec.Code == http.StatusNotFound {
			t.Errorf("GET %s: 404 (route not mounted)", path)
		}
	}
}

// TestSettingsYAMLDownload sets Content-Disposition so browsers save
// the file by name.
func TestSettingsYAMLDownload(t *testing.T) {
	u, _ := newUIForTests(t)
	req := httptest.NewRequest("GET", "/settings/yaml/download", nil)
	rec := httptest.NewRecorder()
	u.settingsYAMLDownload(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("status %d want 200", rec.Code)
	}
	if got := rec.Header().Get("Content-Disposition"); !strings.Contains(got, `filename="compliancekit.yaml"`) {
		t.Errorf("Content-Disposition=%q expected attachment with filename", got)
	}
	if got := rec.Header().Get("Content-Type"); !strings.Contains(got, "yaml") {
		t.Errorf("Content-Type=%q expected yaml MIME", got)
	}
}
